config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  post '/home/guest_sign_in', to: "home#new_guest"
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end
  resources :tweets do
    resource :likes, only: [:create, :destroy]
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end
  resources :events
  resources :videos, only: :index
  resources :ranks, only: :index

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :text, presence: true, length: { maximum: 40 }
  belongs_to :tweet
  belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :event_users, dependent: :destroy
  has_many :users, through: :event_users
  validates :name, :address, :content, presence: true
  mount_uploader :image, ImageUploader
end

app/models/event_user.rb
class EventUser < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tweet_tags, dependent: :destroy
  has_many :tweets, through: :tweet_tags
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :title, presence: true, length: { maximum: 10 }
  validates :text, presence: true, length: { maximum: 200 }
  validates :run, allow_nil: true, numericality: { less_than_or_equal_to: 100 }
  validates :run, allow_nil: true, numericality: { greater_than_or_equal_to: 0 }
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :tweet_tags, dependent: :destroy
  has_many :tags, through: :tweet_tags
  

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

  def self.search(search)
    return Tweet.all unless search
    Tweet.where('title LIKE(?)', "%#{search}%")
  end
  mount_uploader :image, ImageUploader
end

app/models/tweet_tag.rb
class TweetTag < ApplicationRecord
  belongs_to :tweet
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, length: { maximum: 6 }
  validates :introduction, length: { maximum: 200 }
  validates :email, presence: true
  has_many :tweets, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following
  mount_uploader :image, ImageUploader
  
  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(comment_params)
    respond_to do |format|
      format.json
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:text).merge(user_id: current_user.id, tweet_id: params[:tweet_id])
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @event = Event.all
  end

  def new
    @event = Event.new
    @event.users << current_user
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to action: :index, notice: "イベントを作成しました"
    else
      render :new
    end
  end

  private
  def event_params
    params.require(:event).permit(:name, :address, :run, :image, :content, user_ids: [])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def new_guest
    user = User.find_by(name: "ゲスト")
    sign_in user
    redirect_to tweets_path, notice: 'ゲストユーザーとしてログインしました。'
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_tweet, only: [:create, :destroy]
  def create
    like = current_user.likes.build(tweet_id: params[:tweet_id])
    like.save
  end

  def destroy
    like = Like.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
    like.destroy
  end

  private
  def set_tweet
    @tweet = Tweet.find(params[:tweet_id])
  end
end

app/controllers/ranks_controller.rb
class RanksController < ApplicationController
  before_action :authenticate_user!
  def index
    @all_rank = User.joins(:tweets).group(:user_id).order('sum(run) desc').limit(10)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:destroy, :edit, :update, :show]
  before_action :authenticate_user!

  def index
    tweets = params[:tag_ids].present? ? Tag.find(params[:tag_ids]).tweets.order("created_at DESC") : Tweet.includes(:user).order("created_at DESC")
    @tweets = tweets.page(params[:page]).per(12)
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    if @tweet.save
      redirect_to @tweet
    else
      render :new
    end
  end

  def destroy
    @tweet.destroy
    redirect_to @tweet
  end

  def edit
  end

  def update
    if @tweet.update(tweet_params)
      redirect_to @tweet
    else
      render :edit
    end
  end

  def show
    @comment = Comment.new
    @comments = @tweet.comments.includes(:user)
  end

  def search
    tweets = Tweet.search(params[:keyword]).order("created_at DESC")
    @tweets = tweets.page(params[:page]).per(12)
  end

  def youtube
  end


  private
    def tweet_params
      params.require(:tweet).permit(:title, :text, :image, :run, :tag_ids).merge(user_id: current_user.id)
    end

    def set_tweet
      @tweet = Tweet.find(params[:id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :destroy, :update, :show, :followers]
  before_action :authenticate_user!
  def index
    @user = User.find(current_user.id)
    @users = User.includes(:tweets).page(params[:page]).per(10)
  end

  def edit
  end

  def destroy
    @user.destroy
    redirect_to @user
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def show
    @tweets = @user.tweets.order("created_at DESC")
    @ranks = User.joins(:tweets).group(:user_id).order('sum(run) desc')
    @like = Like.where(tweet_id: @tweets.ids).count
    @follows = @user.followings.count
    @followers = @user.followers.count
  end

  def follows
    @user = User.find(current_user.id)
    @users = @user.followings.page(params[:page]).per(10)
  end

  def followers
    @users = @user.followers.page(params[:page]).per(10)
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :image, :introduction)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/tweets/_form.html.haml
= form_with(model: @tweet, local: true) do |f|
  - if @tweet.errors.any?
    %h2= "#{@tweet.errors.full_messages.count}件のエラーが発生しました"
    %ul
      - @tweet.errors.full_messages.each do |message|
        %li= message
  .Input__area
    .Input__area__left
      .Input__area__left__normal
        = f.label :title, "タイトル(10字以内)"
      .Input__area__left__title
        = f.text_field :title, maxlength: "10"
      .Input__area__left__normal
        = f.label :title, "タグ"
      .Input__area__left__tag
        = f.select :tag_ids, [["走行距離", 1], ["運動グッズ", 2], ["大会記録", 3], ["その他", 4]]
      .Input__area__left__normal
        = f.label :run, "走行距離"
      .Input__area__left__run
        = f.number_field :run, step: '0,1', placeholder: "1", min: "0", max: "100"
        %span km
      .Input__area__left__normal
        = f.label :image, "画像"
      .Input__area__left__image
        = f.file_field :image
    .Input__area__right
      .Input__area__right__normal
        = f.label :text, "内容(200字以内)"
      .Input__area__right__text
        = f.text_area :text, rows: "6", maxlength: "200", size: "30x10"
  .Input__button
    = f.submit "投稿・編集する", class: 'submit'

app/views/tweets/_header.html.haml
.Header
  .Header__left
    .Header__left__logo
      = link_to 'Runner Space', root_path
    .Weather
      .day__weather__now
        = "現在の天気 : "
      .dayWeather
      %img.dayWeatherIcon
        = "気温 : "
      .nowTemp
  %ul.header__nav
    -if user_signed_in?
      %li.header__nav__list
        = link_to '投稿一覧', tweets_path
      %li.header__nav__list
        = link_to 'ユーザー一覧', users_path
      %li.header__nav__list
        = link_to 'ランキング', ranks_path
      %li.header__nav__list
        = link_to 'ランニングミュージック', videos_path
      %li.header__nav__list
        = link_to 'ログアウト', destroy_user_session_path, method: :delete
      %li.header__nav__list 
        = link_to user_path(current_user.id) do
          - if current_user.image.present?
            = image_tag current_user.image.url
          - else
            = image_tag "user1.jpg"
    -else
      %li.header__nav__list
        = link_to 'ログイン', new_user_session_path

app/views/tweets/_search.html.haml
.Search
  .Search__title
    = form_with(url: search_tweets_path, local: true, method: :get, class: "search-form") do |f|
      = f.text_field :keyword, class: "search-input"
      = f.submit "検索", class: "search-btn"
  %h2 or
  .Search__tag
    = form_with(model: @tweet, url: tweets_path, local: true, method: :get, id: "submit-form") do |f|
      = f.select :tag_ids, [["タグ検索", 0], ["走行記録", 1], ["運動グッズ", 2], ["大会記録", 3], ["その他", 4]], {}, onchange: "submit(this.form)"
  .Search__new
    = link_to '新規投稿', new_tweet_path

app/views/tweets/_tweet.html.haml
.Article
  .Article__image
    = link_to tweet_path(tweet.id) do
      - if tweet.image.present?
        = image_tag tweet.image.url
      - else
        = image_tag "article1.jpg"
  - if tweet.tags.first.name == "走行記録"
    .Article__tag.color1
      = tweet.tags.first.name
  - elsif tweet.tags.first.name == "運動グッズ"
    .Article__tag.color2
      = tweet.tags.first.name
  - elsif tweet.tags.first.name == "大会記録"
    .Article__tag.color3
      = tweet.tags.first.name
  - else
    .Article__tag.color4
      = tweet.tags.first.name
  .Article__info
    .Article__info__title
      = link_to tweet.title, tweet_path(tweet.id)
    .Article__info__user
      .Article__info__user__icon
        = link_to user_path(tweet.user.id) do
          - if tweet.user.image.present?
            = image_tag tweet.user.image.url
          - else
            = image_tag "user1.jpg"
      .Article__info__user__name
        = link_to tweet.user.name, user_path(tweet.user.id)
    .Article__info__time
      = tweet.created_at.strftime("投稿日時:%m月%d日 %H時%M分")

app/views/tweets/edit.html.haml
.Home
  .Home__top.img1
  .Home__top.img2
  .Home__top.img3
  .Home__top.img4
  .Home__top__body
    .Input
      = render 'form'

app/views/tweets/index.html.haml
.Home__global.img1
  .Home__global__section
    .Content
      = render 'search'
      .Articles
        - @tweets.each do |tweet|
          = render 'tweet', tweet: tweet
    = paginate @tweets

app/views/tweets/new.html.haml
.Home
  .Home__top.img1
  .Home__top.img2
  .Home__top.img3
  .Home__top.img4
  .Home__top__body
    .Input
      = render 'form'

app/views/tweets/search.html.haml
.Home__global.img1
  .Home__global__section
    .Content
      = render 'search'
      .Articles
        - @tweets.each do |tweet|
          = render 'tweet', tweet: tweet
    = paginate @tweets

app/views/tweets/show.html.haml
.Home__global.img2
  .Home__global__section
    .Post
      .Post__section
        .Post__section__main
          .Post__section__main__image
            - if @tweet.image.present?
              = image_tag @tweet.image.url
            - else
              = image_tag "article1.jpg"
          .Post__section__main__info
            - if @tweet.tags.first.name == "走行記録"
              .Post__section__main__info__tag.color1
                = @tweet.tags.first.name
            - elsif @tweet.tags.first.name == "運動グッズ"
              .Post__section__main__info__tag.color2
                = @tweet.tags.first.name
            - elsif @tweet.tags.first.name == "大会記録"
              .Post__section__main__info__tag.color3
                = @tweet.tags.first.name
            - else
              .Post__section__main__info__tag.color4
                = @tweet.tags.first.name
            .Post__section__main__info__link
              = render partial: "likes/like", locals: { tweet: @tweet}
          .Post__section__main__user
            .Post__section__main__user__left
              .Post__section__main__user__left__icon
                = link_to user_path(@tweet.user.id) do
                  - if @tweet.user.image.present?
                    = image_tag @tweet.user.image.url
                  - else
                    = image_tag "user1.jpg"
              .Post__section__main__user__left__name
                = link_to @tweet.user.name, user_path(@tweet.user.id)
            .Post__section__main__user__right
              - if current_user.admin? || (user_signed_in? && current_user.id == @tweet.user_id)
                .Post__section__main__user__right__edit
                  = link_to '編集', edit_tweet_path(@tweet.id), class: "edit"
                .Post__section__main__user__right__delete
                  = link_to '削除', tweet_path(@tweet.id), method: :delete, class: "delete"
        .Post__section__side
          .Post__section__side__title
            = @tweet.title
          .Post__section__side__desc
            = @tweet.text
          - if @tweet.run.present?
            .Post__section__side__top
              = "走行距離"
            .Post__section__side__run
              = "#{@tweet.run}km"
          .Post__section__side__time
            = @tweet.created_at.strftime("投稿日時:%m月%d日 %H時%M分")
      .Post__comment
        .Post__comment__list
          - if @comments
            - @comments.each do |comment|
              - if comment.user_id == @tweet.user_id
                .Post__comment__list__host
                  .Post__comment__list__host__image
                    = link_to user_path(comment.user.id) do
                      - if comment.user.image.present?
                        = image_tag comment.user.image.url
                      - else
                        = image_tag "user1.jpg"
                  .Post__comment__list__host__text
                    %h5= comment.created_at.strftime("%m月%d日 %H時%M分")
                    %p= comment.text
              - else
                .Post__comment__list__post
                  .Post__comment__list__post__text
                    %h5= comment.created_at.strftime("%m月%d日 %H時%M分")
                    %p= comment.text
                  .Post__comment__list__post__image
                    = link_to user_path(comment.user.id) do
                      - if comment.user.image.present?
                        = image_tag comment.user.image.url
                      - else
                        = image_tag "user1.jpg"
        .Post__comment__button
          - if current_user
            = form_with(model: [@tweet, @comment], local: true, id: "new_comment") do |f|
              = f.text_field :text, placeholder: "コメントする", class: "text_area", id: "textbox"
              = f.submit "送信", class: "submit", id: "form__submit"

app/views/users/_follow.html.haml
.Contact
  .Contact__user
    = link_to "ユーザー一覧", users_path
  .Contact__follow
    = link_to "フォロー", follows_user_path(@user.id)
  .Contact__follower
    = link_to "フォロワー", followers_user_path(@user.id)

app/views/users/_user.html.haml
.Index__user
  .Index__user__info
    .Index__user__info__icon
      = link_to user_path(user.id) do
        - if user.image.present?
          = image_tag user.image.url
        - else
          = image_tag "user1.jpg"
    .Index__user__info__group
      .Index__user__info__group__top
        .Index__user__info__group__top__posts
          = "投稿数: #{user.tweets.count}"
      .Index__user__info__group__name
        = link_to user.name, user_path(user.id)
  .Index__user__run
    .Index__user__run__top
      %h2 累計走行距離
    .Index__user__run__bottom
      = "#{user.tweets.sum(:run)}km"

app/views/users/edit.html.haml
.Home
  .Home__top.img1
  .Home__top.img2
  .Home__top.img3
  .Home__top.img4
  .Home__top__body
    .Input
      = form_for(@user) do |f|
        - if @user.errors.any?
          %h2= "#{@user.errors.full_messages.count}件のエラーが発生しました"
          %ul
            - @user.errors.full_messages.each do |message|
              %li= message
        .Input__area
          .Input__area__left
            .Input__area__left__normal
              = f.label :name, "名前(6文字以内)"
            .Input__area__left__title
              = f.text_field :name, maxlength: "6"
            .Input__area__left__normal
              = f.label :email, "E-mail"
            .Input__area__left__title
              = f.email_field :email, class: "text_area"
            .Input__area__left__normal
              = f.label :image, "画像"
            .Input__area__left__image
              = f.file_field :image
          .Input__area__right
            .Input__area__right__normal
              = f.label :introduction, "自己紹介(200字以内)"
            .Input__area__right__text
              = f.text_area :introduction, rows: "6", maxlength: "200", size: "30x10"
        .Input__button
          = f.submit "更新", class: 'submit'

app/views/users/followers.html.haml
.Home__global.img2
  .Home__global__section
    .Content
      = render 'follow', user: @user
      .Index
        - @users.each do |user|
          = render 'user', user: user
    = paginate @users

app/views/users/follows.html.haml
.Home__global.img2
  .Home__global__section
    .Content
      = render 'follow', user: @user
      .Index
        - @users.each do |user|
          = render 'user', user: user
    = paginate @users

app/views/users/index.html.haml
.Home__global.img2
  .Home__global__section
    .Content
      = render 'follow', user: @user
      .Index
        - @users.each do |user|
          = render 'user', user: user
    = paginate @users

app/views/users/show.html.haml
.Home__global.img3
  .Home__global__section
    .Post
      .Privacy
        .Privacy__main
          .Privacy__main__image
            - if @user.image.present?
              = image_tag @user.image.url
            - else
              = image_tag "user1.jpg"
          .Privacy__main__top
            .Privacy__main__top__name
              = @user.name
            .Privacy__main__top__star
              = render partial: "relationships/relationships", locals: {user: @user}
          .Privacy__main__bottom
            = @user.introduction
        .Privacy__side
          .Privacy__side__main
            .Privacy__side__main__top
              = "累計走行距離"
            .Privacy__side__main__bottom
              = "#{@user.tweets.sum(:run)}km"
          .Privacy__side__rank
            .Privacy__side__rank__top
              = "総合順位"
          - @ranks.each.with_index(1) do |rank, i|
            - if rank.id == @user.id
              .Privacy__side__rank__bottom
                = "第#{i}位"
          .Privacy__side__info
            .Privacy__side__info__num
              .Privacy__side__info__num__posts
                = "投稿数: #{@tweets.count}"
              .Privacy__side__info__num__likes
                = icon 'fas', "heart", class: "like"
              = ": #{@like}"
            .Privacy__side__info__user
              .Privacy__side__info__user__follows
                = "フォロー数: #{@follows}"
              .Privacy__side__info__user__followers
                = "フォロワー数: #{@followers}"
            .Privacy__side__info__button
              - if user_signed_in? && current_user.id == @user.id
                - if current_user.name != "ゲスト"
                  .Privacy__side__info__button__edit
                    = link_to "編集", edit_user_path(@user)
              - elsif current_user.admin?
                .Privacy__side__info__button__edit
                  = link_to "編集", edit_user_path(@user)
                .Privacy__side__info__button__delete
                  = link_to "削除", user_path(@user), method: :delete
        .Privacy__articles
          .Privacy__articles__name
            = "#{@user.name}さんの投稿"
          .Privacy__articles__list
            - @tweets.each do |tweet|
              .Privacy__articles__list__post
                .Privacy__articles__list__post__image
                  = link_to tweet_path(tweet.id) do
                    - if tweet.image.present?
                      = image_tag tweet.image.url
                    - else
                      = image_tag "article1.jpg"
                - if tweet.tags.first.name == "走行記録"
                  .Privacy__articles__list__post__tag.color1
                    = tweet.tags.first.name
                - elsif tweet.tags.first.name == "運動グッズ"
                  .Privacy__articles__list__post__tag.color2
                    = tweet.tags.first.name
                - elsif tweet.tags.first.name == "大会記録"
                  .Privacy__articles__list__post__tag.color3
                    = tweet.tags.first.name
                - else
                  .Privacy__articles__list__post__tag.color4
                    = tweet.tags.first.name
                .Privacy__articles__list__post__title
                  = link_to tweet.title, tweet_path(tweet.id)
                .Privacy__articles__list__post__time
                  = tweet.created_at.strftime("投稿日時:%m月%d日 %H時%M分")