config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  post '/home/guest_sign_in', to: "home#new_guest"
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end
  resources :tweets do
    resource :likes, only: [:create, :destroy]
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end
  resources :events
  resources :videos, only: :index
  resources :ranks, only: :index

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :text, presence: true, length: { maximum: 40 }
  belongs_to :tweet
  belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :event_users, dependent: :destroy
  has_many :users, through: :event_users
  validates :name, :address, :content, presence: true
  mount_uploader :image, ImageUploader
end

app/models/event_user.rb
class EventUser < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tweet_tags, dependent: :destroy
  has_many :tweets, through: :tweet_tags
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :title, presence: true, length: { maximum: 10 }
  validates :text, presence: true, length: { maximum: 200 }
  validates :run, allow_nil: true, numericality: { less_than_or_equal_to: 100 }
  validates :run, allow_nil: true, numericality: { greater_than_or_equal_to: 0 }
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :tweet_tags, dependent: :destroy
  has_many :tags, through: :tweet_tags
  

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

  def self.search(search)
    return Tweet.all unless search
    Tweet.where('title LIKE(?)', "%#{search}%")
  end
  mount_uploader :image, ImageUploader
end

app/models/tweet_tag.rb
class TweetTag < ApplicationRecord
  belongs_to :tweet
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, length: { maximum: 6 }
  validates :introduction, length: { maximum: 200 }
  validates :email, presence: true
  has_many :tweets, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following
  mount_uploader :image, ImageUploader
  
  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @event = Event.all
  end

  def new
    @event = Event.new
    @event.users << current_user
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to action: :index, notice: "イベントを作成しました"
    else
      render :new
    end
  end

  private
  def event_params
    params.require(:event).permit(:name, :address, :run, :image, :content, user_ids: [])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def new_guest
    user = User.find_by(name: "ゲスト")
    sign_in user
    redirect_to tweets_path, notice: 'ゲストユーザーとしてログインしました。'
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_tweet, only: [:create, :destroy]
  def create
    like = current_user.likes.build(tweet_id: params[:tweet_id])
    like.save
  end

  def destroy
    like = Like.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
    like.destroy
  end

  private
  def set_tweet
    @tweet = Tweet.find(params[:tweet_id])
  end
end

app/controllers/ranks_controller.rb
class RanksController < ApplicationController
  before_action :authenticate_user!
  def index
    @all_rank = User.joins(:tweets).group(:user_id).order('sum(run) desc').limit(10)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:destroy, :edit, :update, :show]
  before_action :authenticate_user!

  def index
    tweets = params[:tag_ids].present? ? Tag.find(params[:tag_ids]).tweets.order("created_at DESC") : Tweet.includes(:user).order("created_at DESC")
    @tweets = tweets.page(params[:page]).per(12)
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    if @tweet.save
      redirect_to @tweet
    else
      render :new
    end
  end

  def destroy
    @tweet.destroy
    redirect_to @tweet
  end

  def edit
  end

  def update
    if @tweet.update(tweet_params)
      redirect_to @tweet
    else
      render :edit
    end
  end

  def show
    @comment = Comment.new
    @comments = @tweet.comments.includes(:user)
  end

  def search
    tweets = Tweet.search(params[:keyword]).order("created_at DESC")
    @tweets = tweets.page(params[:page]).per(12)
  end

  def youtube
  end


  private
    def tweet_params
      params.require(:tweet).permit(:title, :text, :image, :run, :tag_ids).merge(user_id: current_user.id)
    end

    def set_tweet
      @tweet = Tweet.find(params[:id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :destroy, :update, :show, :followers]
  before_action :authenticate_user!
  def index
    @user = User.find(current_user.id)
    @users = User.includes(:tweets).page(params[:page]).per(10)
  end

  def edit
  end

  def destroy
    @user.destroy
    redirect_to @user
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def show
    @tweets = @user.tweets.order("created_at DESC")
    @ranks = User.joins(:tweets).group(:user_id).order('sum(run) desc')
    @like = Like.where(tweet_id: @tweets.ids).count
    @follows = @user.followings.count
    @followers = @user.followers.count
  end

  def follows
    @user = User.find(current_user.id)
    @users = @user.followings.page(params[:page]).per(10)
  end

  def followers
    @users = @user.followers.page(params[:page]).per(10)
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :image, :introduction)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.haml
.Home__global.img3
  .Home__global__section
    .Event
      = link_to 'イベントを開催する', new_event_path
    
    .Content
      .Index
        - @event.each do |event|
          .Index__user
            .Index__user__info
              .Index__user__info__icon
                = link_to event_path(event) do
                  - if event.image.present?
                    = image_tag event.image.url
                  - else
                    = image_tag "user1.jpg"
              .Index__user__info__group
                .Index__user__info__group__top
                  .Index__user__info__group__top__posts
                    = "参加者: #{event.users.count}"
                .Index__user__info__group__name
                  = link_to event.name, user_path(event.users.ids)
            .Index__user__run
              .Index__user__run__top
                %h2 累計走行距離
              .Index__user__run__bottom

app/views/events/new.html.haml
.Home
  .Home__top.img1
  .Home__top.img2
  .Home__top.img3
  .Home__top.img4
  .Home__top__body
    .Input
      = form_with(model: @event, local: true) do |f|
        - if @event.errors.any?
          %h2= "#{@event.errors.full_messages.count}件のエラーが発生しました"
          %ul
            - @event.errors.full_messages.each do |message|
              %li= message
        .Input__area
          .Input__area__left
            .Input__area__left__normal
              = f.label :name, "タイトル(10字以内)"
            .Input__area__left__title
              = f.text_field :name, maxlength: "10"
            = f.collection_check_boxes :user_ids, User.all, :id, :name
            .Input__area__left__normal
              = f.label :address, "場所"
            .Input__area__left__title
              = f.text_field :address
            .Input__area__left__normal
              = f.label :run, "走行距離(予定)"
            .Input__area__left__run
              = f.number_field :run, step: '0,1', placeholder: "1", min: "0", max: "100"
              %span km
            .Input__area__left__normal
              = f.label :image, "画像"
            .Input__area__left__image
              = f.file_field :image
          .Input__area__right
            .Input__area__right__normal
              = f.label :content, "内容(200字以内)"
            .Input__area__right__text
              = f.text_area :content, rows: "6", maxlength: "200", size: "30x10"
        .Input__button
          = f.submit "作成・編集する", class: 'submit'

app/views/home/index.html.haml
.Home
  .Home__top.img1
  .Home__top.img2
  .Home__top.img3
  .Home__top.img4
  .Home__top__body
    %h1.Main__logo Runner Space
    %p.Main__copy
      %br 走る事が大好きな人々が集まって 
      %br 走る事に対しての熱い思いや、情報、グッズを共有するサイトです
    .Main__button
      .Main__button__signup
        = link_to "会員登録", new_user_registration_path, class: "btn"
      .Main__button__signin
        = link_to "ログイン", new_user_session_path, class: "btn"
      .Main__button__guest
        = link_to "ゲストログイン", home_guest_sign_in_path, method: :post, class: "btn"

app/views/likes/_like.html.haml
- if user_signed_in?
  - if current_user.id != tweet.user_id
    - if tweet.liked_by?(current_user)
      = link_to tweet_likes_path(tweet.id), method: :delete, id: "like-button", remote: true do
        = icon 'fas', "heart", class: "like"
    - else
      = link_to tweet_likes_path(tweet.id), method: :post, id: "like-button", remote: true do
        = icon 'far', "heart", class: "unlike"
    = tweet.likes.count

app/views/likes/create.js.haml
$(".Post__section__main__info__link").html("#{escape_javascript(render partial: 'likes/like', locals: { tweet: @tweet })}");

app/views/likes/destroy.js.haml
$(".Post__section__main__info__link").html("#{escape_javascript(render partial: 'likes/like', locals: { tweet: @tweet })}");